const students = [
  {
    id: 1,
    name: "Shazil Khan",
    email: "shazil.akn@gmail.com",
    phone: "+92-300-1234567",
    course: "PSDC",
    courseId: 1,
    status: "active",
    enrollmentDate: "2024-01-15",
    address: "Karachi, Pakistan",
    age: 22,
    gender: "Male",
  },
  {
    id: 2,
    name: "Fatima Khan",
    email: "fatima.khan@student.edu",
    phone: "+92-301-2345678",
    course: "Data Science",
    courseId: 2,
    status: "active",
    enrollmentDate: "2024-02-01",
    address: "Lahore, Pakistan",
    age: 21,
    gender: "Female",
  },
  {
    id: 3,
    name: "Muhammad Ali",
    email: "muhammad.ali@student.edu",
    phone: "+92-302-3456789",
    course: "Mobile App Development",
    courseId: 3,
    status: "active",
    enrollmentDate: "2024-01-20",
    address: "Islamabad, Pakistan",
    age: 23,
    gender: "Male",
  },
  {
    id: 4,
    name: "Aisha Ahmed",
    email: "aisha.ahmed@student.edu",
    phone: "+92-303-4567890",
    course: "Web Development",
    courseId: 1,
    status: "active",
    enrollmentDate: "2024-02-10",
    address: "Karachi, Pakistan",
    age: 20,
    gender: "Female",
  },
  {
    id: 5,
    name: "Hassan Malik",
    email: "hassan.malik@student.edu",
    phone: "+92-304-5678901",
    course: "Data Science",
    courseId: 2,
    status: "inactive",
    enrollmentDate: "2023-12-15",
    address: "Lahore, Pakistan",
    age: 24,
    gender: "Male",
  },
];

export default students;
